GoldenSweets/Controllers/CakeController.cs
using GoldenSweets.Core;
using GoldenSweets.Core.Models;
using GoldenSweets.Core.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Threading.Tasks;

namespace GoldenSweets.Controllers
{
    [Route("/cakes")]
    public class CakeController : Controller
    {
        private readonly ICakeRepository _cakeRepository;
        private readonly IRatingRepository _ratingRepository;
        private readonly ICategoryRepository _categoryRepository;


        public CakeController(ICakeRepository cakeRepository, IRatingRepository ratingRepository, ICategoryRepository categoryRepository)
        {
            _cakeRepository = cakeRepository;
            _ratingRepository = ratingRepository;
            _categoryRepository = categoryRepository;
        }

        [HttpGet("{category?}")]
        public async Task<IActionResult> List(string category)
        {
            var selectedCategory = !string.IsNullOrWhiteSpace(category) ? category : null;
            var cakesListViewModel = new CakesListViewModel
            {
                Cakes = await _cakeRepository.GetCakes(selectedCategory),
                CurrentCategory = selectedCategory ?? "All Cakes"
            };
            for (int i =0; i < cakesListViewModel.Cakes.Count; i++)
            {
                string rating = await _ratingRepository.GetRatingNumberByCake(cakesListViewModel.Cakes[i].Id);
                cakesListViewModel.Cakes[i].Rating = rating;
            }
            return View(cakesListViewModel);
        }

        [HttpGet("details/{id}")]
        public async Task<IActionResult> Details(int id)
        {
            CakeDetailRatingViewModel ratingModel = new CakeDetailRatingViewModel();
            var rating = await _ratingRepository.GetUserRatingByCakeAsync(id);
            ratingModel.CakeId = id;
            if(rating != null)
            ratingModel.Value = rating.Value ;
            var cake = await _cakeRepository.GetCakeById(id);
            ratingModel.cake = cake;
            return View(ratingModel);
        }

        [HttpPost("Rate")]
        public async Task<IActionResult> Details([Bind("Value,CakeId")] CakeDetailRatingViewModel model)
        {
            var existRating = await _ratingRepository.GetUserRatingByCakeAsync(model.CakeId);
            if(existRating != null)
            {
                existRating.Value = model.Value;
                existRating.Cake = await model.LoadCake(_cakeRepository);
                _ratingRepository.UpdateRating(existRating);
            }
            else
            {
                Rating rating = new Rating();
                rating.CakeId = model.CakeId;
                rating.Value = model.Value;
                rating.UserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                await _ratingRepository.AddRatingAsync(rating);
            }
            model.cake = await model.LoadCake(_cakeRepository);
            return View(model);
        }

    }
}

GoldenSweets/Controllers/GalleryImagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GoldenSweets.Core.Models;
using GoldenSweets.Persistence;
using Microsoft.AspNetCore.Authorization;

namespace GoldenSweets.Controllers
{
    [Authorize(Roles = "Admin")]
    public class GalleryImagesController : Controller
    {
        private readonly GoldenSweetsDbContext _context;

        public GalleryImagesController(GoldenSweetsDbContext context)
        {
            _context = context;
        }

        // GET: GalleryImages
        public async Task<IActionResult> Index()
        {
            var GoldenSweetsDbContext = _context.GalleryImages.Include(g => g.Gallery);
            return View(await GoldenSweetsDbContext.ToListAsync());
        }

        // GET: GalleryImages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var galleryImage = await _context.GalleryImages
                .Include(g => g.Gallery)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (galleryImage == null)
            {
                return NotFound();
            }

            return View(galleryImage);
        }

        // GET: GalleryImages/Create
        public IActionResult Create()
        {
            ViewData["GalleryId"] = new SelectList(_context.Galleries, "Id", "Name");
            return View();
        }

        // POST: GalleryImages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Id,Label,Url,Selected,GalleryId")] GalleryImage galleryImage)
        {
            if (ModelState.IsValid)
            {
                _context.Add(galleryImage);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GalleryId"] = new SelectList(_context.Galleries, "Id", "Name", galleryImage.GalleryId);
            return View(galleryImage);
        }

        // GET: GalleryImages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var galleryImage = await _context.GalleryImages.SingleOrDefaultAsync(m => m.Id == id);
            if (galleryImage == null)
            {
                return NotFound();
            }
            ViewData["GalleryId"] = new SelectList(_context.Galleries, "Id", "Name", galleryImage.GalleryId);
            return View(galleryImage);
        }

        // POST: GalleryImages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Label,Url,Selected,GalleryId")] GalleryImage galleryImage)
        {
            if (id != galleryImage.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(galleryImage);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GalleryImageExists(galleryImage.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GalleryId"] = new SelectList(_context.Galleries, "Id", "Name", galleryImage.GalleryId);
            return View(galleryImage);
        }

        // GET: GalleryImages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var galleryImage = await _context.GalleryImages
                .Include(g => g.Gallery)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (galleryImage == null)
            {
                return NotFound();
            }

            return View(galleryImage);
        }

        // POST: GalleryImages/Delete/5
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var galleryImage = await _context.GalleryImages.SingleOrDefaultAsync(m => m.Id == id);
            _context.GalleryImages.Remove(galleryImage);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GalleryImageExists(int id)
        {
            return _context.GalleryImages.Any(e => e.Id == id);
        }
    }
}

GoldenSweets/Controllers/ShoppingCartController.cs
using GoldenSweets.Core.Models;
using GoldenSweets.Core.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace GoldenSweets.Controllers
{
    [Authorize]
    public class ShoppingCartController : Controller
    {
        private readonly ICakeRepository _cakeRepository;
        private readonly IShoppingCartService _shoppingCart;

        public ShoppingCartController(ICakeRepository cakeRepository, IShoppingCartService shoppingCart)
        {
            _cakeRepository = cakeRepository;
            _shoppingCart = shoppingCart;
        }

        public async Task<IActionResult> Index()
        {
            await _shoppingCart.GetShoppingCartItemsAsync();
            var shoppingCartCountTotal = await _shoppingCart.GetCartCountAndTotalAmmountAsync();
            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartItemsTotal = shoppingCartCountTotal.ItemCount,
                ShoppingCartTotal = shoppingCartCountTotal.TotalAmmount,
            };


            return View(shoppingCartViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddToShoppingCart(int cakeId)
        {
            var selectedCake = await _cakeRepository.GetCakeById(cakeId);
            if (selectedCake == null)
            {
                return NotFound();
            }

            await _shoppingCart.AddToCartAsync(selectedCake);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> RemoveFromShoppingCart(int cakeId)
        {
            var selectedCake = await _cakeRepository.GetCakeById(cakeId);
            if (selectedCake == null)
            {
                return NotFound();
            }

            await _shoppingCart.RemoveFromCartAsync(selectedCake);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> RemoveAllCart()
        {
            await _shoppingCart.ClearCartAsync();
            return RedirectToAction("Index");
        }
    }
}

GoldenSweets/Views/Shared/AccountDropDown.cshtml
<a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Hi, @(User.Identity.Name ?? "User")!
</a>
<div class="dropdown-menu" aria-labelledby="navbarDropdown">
    @if (!User.Identity.IsAuthenticated)
    {
        <a asp-action="login" asp-controller="account" class="dropdown-item">Login</a>
        <a asp-action="register" asp-controller="account" class="dropdown-item">Register</a>
    }
    else
    {
        <a asp-action="myOrder" asp-controller="order" class="dropdown-item">My Order</a>
        <form method="post" asp-action="logout" asp-controller="account" class="no-padding-margin dropdown-item">
            <button class="btn dropdown-item btn-no-effect">logout</button>
        </form>

        if (User.IsInRole("Admin"))
        {

            <div class="dropdown-divider"></div>
            <a class="dropdown-item" asp-action="AllOrders" asp-controller="admin">Gerer Commandes</a>
            <a class="dropdown-item" asp-action="ManageCakes" asp-controller="admin">Gerer Articles</a>
            <a class="dropdown-item" asp-action="Index" asp-controller="GalleryImages">Gerer Images</a>
        }
    }
</div>

GoldenSweets/Views/Shared/AddOrEditCake.cshtml
@model CakeCreateUpdateViewModel
<div class="row">
    <div class="col-md-6">
        <form method="post">
            <div asp-validation-summary="ModelOnly"></div>
            <div class="form-group">
                <label asp-for="CakeDto.Name"></label>
                <input asp-for="CakeDto.Name" class="form-control" />
                <span asp-validation-for="CakeDto.Name"></span>
            </div>
            <div class="form-group">
                <label asp-for="CakeDto.CategoryId"></label>
                <select class="custom-select" asp-for="CakeDto.CategoryId">
                    <option value=""></option>
                    @foreach (var category in Model.Categories)
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
                <span asp-validation-for="CakeDto.CategoryId"></span>
            </div>
            <div class="form-group">
                <label asp-for="CakeDto.ShortDescription"></label>
                <input asp-for="CakeDto.ShortDescription" class="form-control" />
                <span asp-validation-for="CakeDto.ShortDescription"></span>
            </div>
            <div class="form-group">
                <label asp-for="CakeDto.LongDescription"></label>
                <textarea asp-for="CakeDto.LongDescription" class="form-control"></textarea>
                <span asp-validation-for="CakeDto.LongDescription"></span>
            </div>
            <div class="form-group">
                <label asp-for="CakeDto.Price"></label>
                <input asp-for="CakeDto.Price" class="form-control" />
                <span asp-validation-for="CakeDto.Price"></span>
            </div>
            <div class="form-group">
                <label asp-for="CakeDto.ImageUrl"></label>
                <input asp-for="CakeDto.ImageUrl" class="form-control" />
                <span asp-validation-for="CakeDto.ImageUrl"></span>
            </div>
            <div class="form-check form-group">
                <input type="checkbox" class="form-check-input" asp-for="CakeDto.IsCakeOfTheWeek">
                <label class="form-check-label" asp-for="CakeDto.IsCakeOfTheWeek"></label>
                <span asp-validation-for="CakeDto.IsCakeOfTheWeek"></span>
            </div>
            <div class="form-group">
                <button class="btn buy-now-btn">Save</button>
            </div>
        </form>
    </div>
</div>

GoldenSweets/Views/Shared/CakeView.cshtml
@model CakeAndRating

<div class="col-lg-4 col-md-6 col-sm-6">
    <div class="card" style="" onclick="javascript:window.location.href='/cakes/details/@Model.Id'">
        <img class="card-img-top" src="@Model.ImageUrl" alt="@Model.Name">
        <div class="card-body">
            <h5 class="card-title d-inline float-left">
                @Model.Name  rating : @Model.Rating
            </h5>
            <p class="card-text d-inline float-right">@Model.Price.ToString("c")</p>
            <p class="card-text card-short-description"><i>@Model.ShortDescription</i></p>
            <form asp-action="AddToShoppingCart"
                  asp-controller="ShoppingCart"
                  asp-route-cakeId="@Model.Id"
                  method="post">

                <button class="btn btn-primary buy-now-btn float-right">Buy Now</button>
            </form>

        </div>
    </div>
</div>

GoldenSweets/Views/Shared/Category.cshtml
<a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Catagory
</a>
<div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <a class="dropdown-item" asp-controller="/cakes" asp-action="Vanilla Cakes">Vanilla Cakes</a>
    <a class="dropdown-item" asp-controller="/cakes" asp-action="Chocolate Cakes">Chocolate Cakes</a>
    <a class="dropdown-item" asp-controller="/cakes" asp-action="Fruit Cakes">Fruit Cakes</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" asp-controller="/cakes" asp-action="">All Cakes</a>
</div>

GoldenSweets/Views/Shared/OrderList.cshtml
@model IEnumerable<MyOrderViewModel>

@if (Model?.Count() <= 0)
{
    <div>
        <p>No Order so far! Go ahead and place some order.</p>
    </div>
    return;
}

<table class="table table-striped text-center">
    <thead>
        <tr>
            <th>Billing Address</th>
            <th>Order Summary</th>
            <th>Total Ammount</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var order in Model)
        {
            <tr>

                <td class="text-justify">
                    <div>
                        @order.OrderPlaceDetails.FirstName @order.OrderPlaceDetails.LastName,
                        @order.OrderPlaceDetails.AddressLine1
                        <div>
                            @order.OrderPlaceDetails.AddressLine2
                        </div>
                    </div>
                    <div>
                        @order.OrderPlaceDetails.City,
                        @order.OrderPlaceDetails.State
                    </div>
                    <div>
                        @order.OrderPlaceDetails.ZipCode
                    </div>
                    <div>@order.OrderPlaceDetails.PhoneNumber</div>
                    <div>@order.OrderPlaceDetails.Email</div>
                    <br />
                    <div>
                        @order.OrderPlacedTime.Date.ToString("dd/MM/yyyy")
                    </div>

                </td>


                <td>
                    <table class="table">
                        <tbody>
                            @foreach (var item in order.CakeOrderInfos)
                            {
                                <tr>
                                    <td>
                                        @item.Name
                                    </td>
                                    <td>
                                        @item.Price.ToString("c") * @item.Qty

                                    </td>
                                </tr>

                            }
                        </tbody>

                    </table>
                </td>
                <td>
                    @order.OrderTotal.ToString("c")
                </td>
            </tr>

        }

    </tbody>
</table>

GoldenSweets/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>GoldenSweets</title>
    <environment names="Development">
        <script src="~/dist/main.js"></script>
        <link rel="stylesheet" href="~/css/GoldSweets.css" />
    </environment>
    <environment names="Production">
        <script src="~/dist/main.js" asp-append-version="true"></script>
        <link rel="stylesheet" href="~/css/GoldSweets.css" />
    </environment>


</head>
<body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="/">
                <i class="fa fa-shopping-bag" aria-hidden="true"></i>
                GoldenSweets
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        @Html.Partial("Category")
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="contact" asp-action="">Contact Us</a>
                    </li>
                </ul>

                <ul class="navbar-nav">
                    <li>
                        <a class="nav-link" href="/shoppingcart">
                            Cart
                            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                            @await Component.InvokeAsync("ShoppingCartSummary")
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        @Html.Partial("AccountDropDown")
                    </li>
                </ul>

            </div>
        </div>
    </nav>

    <main role="main" class="container">
        @RenderBody()
    </main>

    <footer class="footer">
        <div class="container">
            <p class="d-inline float-left">Copyright (c) 2018-@(DateTime.Now.Year + 1)</p>
            <p class="d-inline float-right">
                Ritwick Dey
            </p>
        </div>
        @*<email address="example@example.com" content="Contact Us"></email>*@
    </footer>

    @RenderSection("scripts", false)

</body>

</html>

GoldenSweets/Views/Shared/carousel.cshtml
@model List<GalleryImage>

<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        @for (int i = 1; i < Model.Count() ; i += 1)
        {
            <li data-target="#carouselExampleIndicators" data-slide-to="@i"></li>
        }
    </ol>
        
    <div class="carousel-inner">
        <div class="carousel-item active">
            <div class="carousel-item-img">
                <img class="d-block" src="@Model[0].Url" >
            </div>
            <div class="carousel-caption d-none d-md-block">
                <h5>@Model[0].Label</h5>
                <p>Yaamy! Chooclate</p>
            </div>
        </div>

        @for (int i = 1; i < Model.Count() ; i += 1)
        {
            <div class="carousel-item">
                <div class="carousel-item-img">
                    <img class="d-block" src="@Model[i].Url" >
                </div>
                <div class="carousel-caption d-none d-md-block">
                    <h5>@Model[i].Label</h5>
                </div>
            </div>
        }

    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

@section scripts {
    <script>


        $('.carousel').carousel({})


    </script>
}